FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    gcc g++ tesseract-ocr \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
COPY requerimientos.txt .
RUN pip install -r requerimientos.txt
RUN python -m spacy download en_core_web_sm

COPY . /app/
WORKDIR /app
EXPOSE 5000
CMD ["python", "main.py"]